services:
  finetune:
    build:
      context: ./mock_finetune
      dockerfile: Dockerfile
    # Overriding the deploy section with empty resources to remove GPU requirement
    deploy:
      resources:
        reservations:
          devices: []
